### ISSUE TITLE
Location of code for Cross domain semantic parsing via paraphrasing

### ISSUE THREAD

**Issue by sobalgi** [ysu1989/CrossSemparse#1]
The git repo seems to be not containing any code.
Please point me to the right location for the code.
Many thanks,
@sobalgi

**Comment by ysu1989** [comment]
Hi sobalgi,

I finally got time to clean up and document the code. The code is now available. Let me know if you run into any issue with it!

**Comment by sobalgi** [comment]
Hello Mr. Su,

Thanks a lot for providing your original implememtation. I really appreciate your quick response.
Initial run seems to be working fine (no code errors)!!!

I'll run the batch script with gpu and hopefully try to reproduce your original results.
Can you please let me know how long will it take for complete in-domain and cross-domain training and testing on gpu?

Also what does gold canonical utterance and top canonical utterence imply into testing logs?

Also I have gone through you code. I see that you have source.*, target.*, vocab* files already present for each domain. I was wondering if you have some additional preprocessing code used to create tgese files from the original overnight dataset files.

It would be very helpful to have this file as I'm trying to implement it myself.

Many thanks in advance.
Best regards,
Sourabh Balgi,
IISc, Bangalore.
