### ISSUE TITLE
Cross domain training without pretraining

### ISSUE THREAD

**Issue by aayushee** [ysu1989/CrossSemparse#3]
Hi

Could you please let me know whether the Cross domain results for a target domain as published in the paper can be obtained without any in-domain pretraining on that target domain?   

Thanks
Aayushee

**Comment by ysu1989** [comment]
That will be the zero-shot setting which is different from the setting in this paper. You can refer to the following paper for more on that:

Decoupling Structure and Lexicon for Zero-Shot Semantic Parsing - EMNLP 2018
